//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Table
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string IPAddress { get; set; }
        public int ProcessID { get; set; }
        public int ProcessType { get; set; }
        public string ProcessCategoryType { get; set; }
        public System.DateTime ProcessDate { get; set; }
    
        public virtual ProcessType ProcessType1 { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
